# 网站信息
site_name: 陈裕杰的个人网站 # 左上角标题
site_url: https://codezhxs.github.io
site_author: 陈裕杰
site_description: 陈裕杰的个人网站

# [Navigtion]
nav:
  - 算法:
    - algorithm/index.md
    - ABC352(A-F): algorithm/AtCoder/abc352.md
    - ABC351(A-G): algorithm/AtCoder/abc351.md
    - ABC347(A-E): algorithm/AtCoder/abc347.md
    - ABC343(A-G): algorithm/AtCoder/abc343.md
    - ABC342(A-G): algorithm/AtCoder/abc342.md
    - ABC341(A-G): algorithm/AtCoder/abc341.md
    - ABC340(A-F): algorithm/AtCoder/abc340.md
    - ABC335(A-F): algorithm/AtCoder/abc335.md
    - ABC334(A-G): algorithm/AtCoder/abc334.md
    - ABC333(A-F): algorithm/AtCoder/abc333.md
    - ABC332(A-G): algorithm/AtCoder/abc332.md
    - ABC312(A-F): algorithm/AtCoder/abc312.md
    - ABC311(A-G): algorithm/AtCoder/abc311.md
    - ABC310(A-F): algorithm/AtCoder/abc310.md
    - ABC309(A-F): algorithm/AtCoder/abc309.md
    - ABC308(A-G): algorithm/AtCoder/abc308.md
    - 笔记: algorithm/note.md
  
  - 开发:
    - dev/index.md
    # - CPP:
      # - 第1章 开始: dev/cpp/ch1.md
    - Java:
      - 《Java核心技术》笔记:
        - 第2章 Java程序设计环境: dev/java/CoreJava/ch02.md
        - 第3章 Java的基本程序设计结构: dev/java/CoreJava/ch03.md
        - 第4章 对象与类: dev/java/CoreJava/ch04.md
        - 第5章 继承: dev/java/CoreJava/ch05.md
        - 第6章 接口、lambda表达式与内部类: dev/java/CoreJava/ch06.md
        - 第7章 异常、断言和日志: dev/java/CoreJava/ch07.md
        - 第8章 泛型程序设计: dev/java/CoreJava/ch08.md
        - 第9章 集合: dev/java/CoreJava/ch09.md
      - 源码分析:
        - HashMap源码分析: dev/java/SourceCode/HashMap.md
    - 开发环境配置: 
      - 我的PowerShell配置: dev/env/win/my_powershell.md
      - 在Windows中安装gcc: dev/env/win/gcc.md
      - VMware使用Linux速查: dev/env/win/vmware.md
    - hydro OJ运维: dev/myoj.md
  - 随笔:
    - essay/index.md
    - 日记:
      - 日记 | 2024-05 : essay/diary/2024-05.md
      - 日记 | 2024-04 : essay/diary/2024-04.md
      - 日记 | 2023-12 : essay/diary/2023-12.md
      - 日记 | 2023-10 : essay/diary/2023-10.md
  - 归档:
    - 密码学期末复习: archive/crypto.md
    - 图论期末复习: archive/graph.md
  - 其他:
    - others/index.md
    - Latex公式整理: others/latex.md
    - 北京干饭参考表 : others/BJ_food.md
    - 我的PC配置: others/pc.md

# 不会渲染的页面
exclude_docs: |
  /dev/cpp/
  /archive/missing-semester.md

# 会渲染但隐藏起来的页面 可以避免nav警告
not_in_nav: |
  index.md
  /others/BJ_food_delete.md
  /others/Hongya_cave.md
  /algorithm/20240325.md

# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的颜色
      accent: orange # 链接等可交互元件的高亮色 默认indigo
      toggle:
        icon: material/weather-night # 显示的图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  language: zh # 网站的语言 会影响一些自动参数
  features:
    - navigation.instant.progress # 页面加载进度条
    - navigation.tabs # 顶层的Tab
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.top # 在上滑时出现一个返回顶部的按钮
    - navigation.footer # 底部的翻页按钮
    - search.suggest # 搜索建议和补全
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.action.edit # 点击按钮跳转到编辑页面  需要结合 edit_uri 一起使用
    - content.code.copy # 代码块右上角会有一个复制按钮
    - content.tabs.link # 标签可以一次性切换
  
  # 图标都可以更换 见 https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo-icon-bundled
  # 在这里可以搜索内置的图标 https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  icon:
    logo: material/library # 左上角图标
    repo: fontawesome/brands/github #右上角github图标
  # favicon就是网站在浏览器标签页中的图标
  # 在顶级域名后面加一个 /favicon.ico 可以获取网站的favicon
  # favicon: images/favicon.png  

# 右上角的github仓库
repo_url: https://github.com/CodeZHXS/codezhxs.github.io # 跳转的链接
repo_name: codezhxs.github.io # 右上角的名字

edit_uri: edit/main/docs/ #文章的编辑按钮跳转到github仓库的路径

copyright: 陈裕杰 CC-BY-4.0 # 左下角的版权声明

extra:
  social: # [右下角的图标链接]
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/12519995
      name: Bilibili | Jay朝花夕拾杯中酒 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/CodeZHXS
      name: GitHub | CodeZHXS

# extra_javascript:
  # 有时间弄一下快捷键提示
  # 这里可以增加网站的快捷键 https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#keyboard-shortcuts-mkdocsyml
  # - javascripts/shortcuts.js 

# [Extensions]
plugins:
  - search: # 搜索功能
      lang: # 设置支持搜索的语言
        - ch # 还可以换成Jieba字典 见 https://squidfunk.github.io/mkdocs-material/plugins/search/#config.jieba_dict
        - en
  - git-revision-date-localized:
      enable_creation_date: true #在文章下方显示创建时间和更新时间
      fallback_to_build_date: true
      type: iso_date # 日期的格式
  # 有时间的话配置一下博客插件 https://squidfunk.github.io/mkdocs-material/plugins/blog/
  
markdown_extensions:
  - def_list # 启用有序和无序列表
  - pymdownx.tasklist:
      custom_checkbox: true # 任务列表的图标变得更漂亮
  - attr_list # 提供图片左中右对齐以及大小调整功能
  - md_in_html # 图片居中时的可以添加注解
  - toc:
      toc_depth: 6 # 文章目录展开的级数 默认为6 0表示不显示目录
      permalink: true # 各级标题旁边都有一个固定按钮
  - pymdownx.superfences # 代码块高亮的依赖插件
  # - pymdownx.highlight: # 代码块高亮设置
  #     linenums: true # 在代码块左侧添加行号
  #     auto_title: true # 显示编程语言名称
  - pymdownx.tabbed: 
      alternate_style: true # 启用标签功能
  - pymdownx.arithmatex: # latex支持
      generic: true
  - admonition # 警告等 见 https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition的依赖
  - pymdownx.caret # 启用高亮、下划线、删除线
  - pymdownx.mark  # 启用高亮、下划线、删除线
  - pymdownx.tilde # 启用高亮、下划线、删除线
  - pymdownx.emoji: # 启用emoji和icon
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.superfences: # 启用图表
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format


extra_javascript:
  # latex支持 
  # https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  # 用mathjax经常加载不出来，所以换了KaTeX
  # - mkdocs/javascripts/mathjax.js 
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
